package com.swapi.challenge.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import com.fasterxml.jackson.annotation.JsonInclude;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

import java.util.HashMap;
import java.util.Map;


@DynamoDBTable(tableName = "planets")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Planet {

    private String id;
    private String name;
    private String climate;
    private String terrain;
    private Integer films;


    public Planet() {
    }

    public Planet(Map<String, AttributeValue> plan){
        this.id = plan.get("id").s();
        this.name = plan.get("name").s();
        this.climate = plan.get("climate").s();
        this.terrain = plan.get("terrain").s();
        this.films = Integer.parseInt(plan.get("films").n());
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getClimate() {
        return climate;
    }

    public void setClimate(String climate) {
        this.climate = climate;
    }

    @DynamoDBAttribute
    public String getTerrain() {
        return terrain;
    }

    public void setTerrain(String terrain) {
        this.terrain = terrain;
    }

    @DynamoDBAttribute
    public Integer getFilms() { return this.films; }

    public void setFilms(Integer films) { this.films = films; }

    public Map<String, AttributeValue> mapper() {
        Map<String, AttributeValue> att = new HashMap<>();
        att.put("id", AttributeValue.builder().s(this.id).build());
        att.put("name", AttributeValue.builder().s(this.name).build());
        att.put("climate", AttributeValue.builder().s(this.climate).build());
        att.put("terrain", AttributeValue.builder().s(this.terrain).build());
        att.put("films", AttributeValue.builder().n(String.valueOf(this.films)).build());
        return att;
    }
}