spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/sw
  profiles:
    active: local

amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: teste1
    secretkey: teste1